/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: Global Digital Heritage (https://sketchfab.com/GlobalDigitalHeritage)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bronze-spearhead-c55f7d93414d49008674e29827f93417
Title: Bronze spearhead
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model2(props) {
  const { nodes, materials } = useGLTF("/starship/model2/scene.gltf")
  return (
    <group {...props} dispose={null}>
      <group rotation={[0.2, 1.51, -1.77]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.MUE_1831_Model_6_u1_v1} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.MUE_1831_Model_6_u1_v1} />
      </group>
    </group>
  )
}

useGLTF.preload('/scene.gltf')
