/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf
Author: Al-Deezel (https://sketchfab.com/Al-dezel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/high-detailed-fish-b3ba263918114af183d5f4f859164a1d
Title: High detailed Fish
*/

import React from 'react'
import {useGLTF} from '@react-three/drei'

export function Starship(props) {
  const { nodes, materials } = useGLTF("/starship/model1/scene.gltf")
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.material_0} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/scene.gltf')
